# Generated by Django 5.1.6 on 2025-02-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('cpu', models.PositiveSmallIntegerField(verbose_name='Кол-во ядер процессора')),
                ('ram', models.PositiveSmallIntegerField(verbose_name='Размер ОЗУ')),
                ('hdd', models.PositiveSmallIntegerField(verbose_name='Размер хранилища')),
                ('status', models.CharField(choices=[('started', 'Started'), ('blocked', 'Blocked'), ('stopped', 'Stopped')], default='stopped', max_length=10, verbose_name='Статус сервера')),
            ],
        ),
    ]
